addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"             % "2.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.7.6")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.9.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"        % "3.9.5")
