addSbtPlugin("com.dwijnand"      % "sbt-dynver"   % "4.0.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.2.0")
addSbtPlugin("io.spray"          % "sbt-revolver" % "0.9.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.3")
